language: php

sudo: false

php:
  - 5.5
  - 5.6

before_script:
  - composer install --prefer-source

script: ./vendor/bin/paratest -f --colors -m 2 -p 4 tests

cache:
    directories:
        - vendor
